particles:
  spin: 0.5 # hbar
  coordinates: # m
    # - [[xmin, xmax], [ymin, ymax], [zmin, zmax]]
    - [[-5.0e-9, 5.0e-9], [-5.0e-9, 5.0e-9], [4.375e-9, 4.375e-9]]
sensors:
  spin: 1 # hbar
  init_state: 0 # m_s or 'GHZ'
  coordinates: # m
  # - [x, y, z]
    - [ 2.02072594e-09,          0, 0]
    - [-1.01036297e-09,  1.75e-09,  0]
    - [-1.01036297e-09, -1.75e-09,  0]
# Magnetic field (z direction)
B: 0.05121341898643826 # T
# Evolution time
t: 1.0e-6 # s
# Number of configurations (list of integers)
nconfigs: [10000]