particles:
  spin: 0.5 # hbar
  coordinates: # m
    # - [[xmin, xmax], [ymin, ymax], [zmin, zmax]]
    - [[-5.0e-9, 5.0e-9], [-5.0e-9, 5.0e-9], [4.375e-9, 4.375e-9]]
sensors:
  spin: 1 # hbar
  init_state: 0 # m_s or 'GHZ'
  coordinates: # m
  # - [x, y, z]
    - [-3.5e-9, 0, 0]
    - [      0, 0, 0]
    - [ 3.5e-9, 0, 0]
# Magnetic field (z direction)
B: 0.05121341898643826 # T
# Evolution time
t: 4.80560108621743e-07 # s
# Number of configurations (list of integers)
nconfigs: [10000]